version: '3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nopassword
      - MYSQL_DATABASE=game
    ports:
      - "3306:3306"
  
  web:
    build: .
    ports:
      - 8080:80